config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import re_path

urlpatterns = [
    re_path(
        r"^" + settings.URL_PREFIX,
        include(
            [
                path("admin/", admin.site.urls),
                # TODO Namespace the apps and put them on sub urls.
                path("", include("users.urls")),
                path("", include("fleets.urls")),
                path("", include("bank.urls")),
                path("", include("items.urls")),
                path("", include("contracts.urls")),
                path("", include("market.urls")),
                path("", include("ownership.urls")),
                path("", include("core.urls")),
                path(
                    "api/", include("rest_framework.urls", namespace="rest_framework")
                ),
                path("", include("django_prometheus.urls")),
                path("accounts/", include("allauth.urls")),
                path("tinymce/", include("tinymce.urls")),
                path("comments/", include("django_comments.urls")),
                path("forms/", include("user_forms.urls")),
                path("notifications/", include("notifications.urls")),
                path("hordak/", include("hordak.urls", namespace="hordak")),
                path("venmo/", include("venmo.urls")),
                path("mapbot/", include("mapbot.urls")),
                path("industry/", include("industry.urls")),
                path("pricing/", include("pricing.urls")),
            ]
            + settings.ENV_SPECIFIC_URLS
        ),
    )
]


def core_handler500(request):
    return render(request, "core/500.html", status=500)


handler500 = core_handler500

goosetools/industry/urls.py
from django.urls import path
from django.urls.conf import include
from rest_framework import routers

from goosetools.industry.views import (
    ShipOrderViewSet,
    ShipViewSet,
    edit_olg,
    edit_ship,
    new_olg,
    new_ship,
    olg_list,
    ship_dashboard,
    shiporders_contract_confirm,
    shiporders_create,
    shiporders_view,
)

app_name = "industry"

router = routers.DefaultRouter()
router.register(r"shiporder", ShipOrderViewSet)
router.register(r"ship", ShipViewSet)

urlpatterns = [
    path(
        "shiporder/<int:pk>/contract_confirm",
        shiporders_contract_confirm,
        name="shiporders_contract_confirm",
    ),
    path("shiporder/form_create", shiporders_create, name="shiporders_create"),
    path("shiporder/", shiporders_view, name="shiporders_view"),
    path("admin/olg", olg_list, name="olg_list"),
    path("admin/olg/new", new_olg, name="new_olg"),
    path("admin/olg/<int:pk>/edit", edit_olg, name="edit_olg"),
    path("admin/ship/new", new_ship, name="new_ship"),
    path("admin/ship/<int:pk>/edit", edit_ship, name="edit_ship"),
    path("admin/ships", ship_dashboard, name="ship_dashboard"),
    path("shiporder/", include((router.urls))),
]

goosetools/industry/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.db.models.aggregates import Max
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_fsm import FSMField, transition
from djmoney.models.fields import MoneyField
from djmoney.money import Money

from goosetools.users.models import Character, GooseUser


def to_isk(num):
    return Money(amount=round(num, 2), currency="EEI")


class OrderLimitGroup(models.Model):
    name = models.TextField()
    days_between_orders = models.PositiveIntegerField()

    def ships(self):
        return [ship.name for ship in self.ship_set.all()]  # type:ignore

    def __str__(self):
        return f"{self.name} - days_between_orders:{self.days_between_orders}"


class Ship(models.Model):
    name = models.TextField(unique=True)
    tech_level = models.PositiveIntegerField()
    free = models.BooleanField(default=False)
    order_limit_group = models.ForeignKey(
        OrderLimitGroup, on_delete=models.SET_NULL, null=True, blank=True
    )
    isk_price = MoneyField(
        max_digits=20, decimal_places=2, default_currency="EEI", null=True, blank=True
    )
    eggs_price = MoneyField(
        max_digits=20, decimal_places=2, default_currency="EEI", null=True, blank=True
    )
    prices_last_updated = models.DateTimeField(null=True, blank=True)

    def valid_price(self):
        now_minus_1_hour = timezone.now() - timezone.timedelta(hours=1)
        return (
            self.isk_price is not None
            and self.eggs_price is not None
            and self.prices_last_updated is not None
            and self.prices_last_updated >= now_minus_1_hour
        )

    def clean(self):
        if not self.free and self.order_limit_group is not None:
            raise ValidationError(
                _(
                    "A Ship cannot be free and in a Order Limit Group. Either remove the group or make the ship free."
                )
            )

    def total_order_quantity(self):
        result = self.shiporder_set.aggregate(total=Sum("quantity"))  # type: ignore
        if result:
            return result["total"]
        else:
            return 0

    def total_order_quantity_last_month(self):
        now = timezone.now()
        now_minus_1_month = now - timezone.timedelta(weeks=4)
        result = self.shiporder_set.filter(created_at__gt=now_minus_1_month).aggregate(
            # type: ignore
            total=Sum("quantity")
        )
        if result:
            return result["total"]
        else:
            return 0

    def last_order(self):
        result = self.shiporder_set.aggregate(max=Max("created_at"))  # type: ignore
        if result:
            return result["max"]
        else:
            return "Never Ordered"

    def total_isk_and_eggs_quantity(self):
        result = self.shiporder_set.aggregate(total=Sum("price"))  # type: ignore
        if result:
            return result["total"]
        else:
            return 0

    def total_isk_and_eggs_quantity_last_month(self):
        now = timezone.now()
        now_minus_1_month = now - timezone.timedelta(weeks=4)
        result = self.shiporder_set.filter(created_at__gt=now_minus_1_month).aggregate(
            # type: ignore
            total=Sum("price")
        )
        if result:
            return result["total"]
        else:
            return 0

    # pylint: disable=signature-differs
    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    def __str__(self):
        display = f"{self.name} (T{self.tech_level}) "
        if self.free:
            display = display + " - FREE"
        return display


class ShipOrder(models.Model):
    PAYMENT_METHODS = [
        ("eggs", "eggs"),
        ("isk", "isk"),
        ("free", "free"),
        ("srp", "srp"),
    ]
    recipient_character = models.ForeignKey(Character, on_delete=models.CASCADE)
    assignee = models.ForeignKey(
        GooseUser, on_delete=models.CASCADE, null=True, blank=True
    )
    contract_made = models.BooleanField(default=False)
    ship = models.ForeignKey(Ship, on_delete=models.CASCADE)
    uid = models.TextField(unique=True)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField()
    blocked_until = models.DateTimeField(null=True, blank=True)
    state = FSMField(default="not_started")
    notes = models.TextField(blank=True)
    payment_method = models.TextField(choices=PAYMENT_METHODS)
    price = MoneyField(
        max_digits=20, decimal_places=2, default_currency="EEI", null=True, blank=True
    )
    payment_taken = models.BooleanField(default=False)

    def paid_ship(self):
        return self.payment_method in {"eggs", "isk"}

    def payment_actually_taken(self):
        return not self.paid_ship() or self.payment_taken

    def needs_manual_price(self):
        return self.paid_ship() and not self.payment_taken and not self.price

    def currently_blocked(self) -> bool:
        if self.blocked_until is not None:
            return timezone.now() < self.blocked_until
        else:
            return False

    def __str__(self):
        return f"ShipOrder({self.id}) - {self.ship}*{self.quantity}->{self.recipient_character}:{self.uid}"

    def availible_transitions(self):
        # pylint: disable=no-member
        return {
            t.name: t for t in self.get_available_state_transitions()
        }  # type: ignore

    def availible_transition_names(self):
        # pylint: disable=no-member
        return [t.name for t in self.get_available_state_transitions()]  # type: ignore

    @transition(field=state, source="not_started", target="inventing")
    def inventing(self):
        pass

    @transition(field=state, source="inventing", target="awaiting_production_slot")
    def awaiting_production_slot(self):
        pass

    @transition(
        field=state,
        source=["inventing", "awaiting_production_slot", "not_started"],
        target="building",
    )
    def building(self):
        pass

    @transition(field=state, source=["building", "not_started"], target="audit")
    def audit(self):
        pass

    @transition(
        field=state,
        source=["audit", "missing_contract"],
        target="waiting_on_gift_quota",
    )
    def waiting_on_gift_quota(self):
        pass

    @transition(
        field=state,
        source=["audit", "missing_contract", "not_started", "waiting_on_gift_quota"],
        target="sent",
    )
    def sent(self):
        pass

    @transition(field=state, source="audit", target="missing_contract")
    def missing_contract(self):
        pass

    @transition(field=state, source="*", target="not_started")
    def reset(self):
        pass

    class Meta:
        indexes = [models.Index(fields=["-created_at"])]

goosetools/industry/forms.py
from django import forms
from django.forms.models import ModelChoiceField
from django.forms.widgets import CheckboxSelectMultiple, HiddenInput

from goosetools.industry.models import OrderLimitGroup, Ship, ShipOrder
from goosetools.users.models import Character


class ShipOrderForm(forms.Form):
    recipient_character = forms.ModelChoiceField(
        label="Recipient Character",
        queryset=Character.objects.all(),
        initial=0,
    )
    ship = ModelChoiceField(
        queryset=Ship.objects.all(),
        initial="Vexor Navy Issue",
        widget=forms.Select(attrs={"class": "browser-default"}),
    )
    payment_method = forms.ChoiceField(
        choices=ShipOrder.PAYMENT_METHODS, initial="free"
    )
    notes = forms.CharField(initial="", required=False)
    quantity = forms.IntegerField(min_value=1, initial=1)
    isk_price = forms.IntegerField(min_value=1, widget=HiddenInput(), required=False)
    eggs_price = forms.IntegerField(min_value=1, widget=HiddenInput(), required=False)


class ShipForm(forms.Form):
    name = forms.CharField()
    tech_level = forms.IntegerField(min_value=0)
    free = forms.BooleanField(required=False)
    order_limit_group = forms.ModelChoiceField(
        queryset=OrderLimitGroup.objects.all(), initial=0, required=False
    )


class OrderLimitGroupForm(forms.ModelForm):
    class Meta:
        model = OrderLimitGroup
        fields = ["name", "days_between_orders"]

    ships = forms.ModelMultipleChoiceField(
        queryset=Ship.objects.filter(free=True).order_by("name").all(),
        widget=CheckboxSelectMultiple(),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.fields["ships"].initial = self.instance.ship_set.all()

    # pylint: disable=unused-argument,signature-differs
    def save(self, *args, **kwargs):
        instance = super().save(commit=False)
        self.fields["ships"].initial.update(order_limit_group=None)
        self.cleaned_data["ships"].update(order_limit_group=instance)
        return instance

goosetools/industry/templates/industry/shiporders/contract_confirm.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        <h3>Create Order Contract</h3>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <button class="btn waves-effect waves-light green pulse" type="submit"
                        value="Submit">
                    I CONFIRM I HAVE READ THE BELOW - CLICKING THIS WILL CREATE THE
                    ORDER
                    <i class="material-icons right">send</i>
                </button>
                <h5 class="red-text">Before Submitting Complete These Steps:</h5>
                <div class="col s12 m12">
                    <h6>Follow this GIF:</h6>
                    <span>You must put in the contract's description the following code: </span>
                    <blockquote>
                        {{ ship_order.uid }}
                    </blockquote>
                    {% if ship_order.payment_method == "isk" %}
                        {% if ship_order.valid_price %}
                            <span>You are paying with ISK so you must enter the below price into the "I'll pay" section of the contract.</span>
                            <blockquote>{{ ship_order.price }}</blockquote>
                        {% else %}
                            <span class="red-text">You are paying with ISK however {{ SITE_NAME }} was unable to find a valid price for the ship. {{ PRICE_CONTACT_INFO }}</span>
                        {% endif %}
                    {% endif %}
                    {% if ship_order.blocked_until %}
                        <span class="red-text">This ship order will not be processed until after {{ ship_order.blocked_until }}, make sure the contract you make will not expire by a week after that date by either extending the contract expiry or waiting to make the contract.</span>
                    {% endif %}
                    <img src="{% static "how_to_contract.gif" %}"/>
                </div>
                <div class="col s12 m12">
                    <ol>
                        <li>
                            Make an in-game contract with visibility set to "Alliance"
                        </li>
                        <li>
                            Select Jita IV - Moon 4 ITC as the station location (if you
                            don't see this option buy something cheap there first and it
                            will become visible)
                        </li>
                        <li>
                            You must put in the contract's description the following
                            code:
                            <blockquote>
                                {{ ship_order.uid }}
                            </blockquote>
                        </li>
                        {% if ship_order.payment_method == "isk" %}
                            <li>
                                {% if ship_order.valid_price %}
                                    You are paying with ISK so you must enter the below
                                    price into the "I'll pay" section of the contract.
                                    <blockquote>{{ ship_order.price }}</blockquote>
                                {% else %}
                                    <span class="red-text">You are paying with ISK however {{ SITE_NAME }} was unable to find a valid price for the order. {{ PRICE_CONTACT_INFO }}</span>
                                {% endif %}
                            </li>
                        {% endif %}
                        <li>
                            {% if ship_order.blocked_until %}
                                This ship order will not be processed until after
                                {{ ship_order.blocked_until }}, make sure the contract
                                you make will not expire by a week after that date by
                                either setting the contract expiry to be 2 weeks, or
                                waiting to make the contract until
                                {{ ship_order.blocked_until }}.
                            {% else %}
                                Make sure the expiry is set to 1 week, or 2 weeks for a
                                battleship
                            {% endif %}
                        </li>
                        <li>
                            Scroll down, click 'Add Item' to add the item you ordered
                        </li>
                        <li>
                            Finally, create the contract
                        </li>
                    </ol>
                    <p class="red-text">
                        If you mess up any of these steps, your order might not be
                        filled as the industry team will not be
                        able to find or verify your contract
                    </p>
                </div>
            </div>
        </form>
    </div>


{% endblock %}

goosetools/industry/templates/industry/shiporders/create.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        <h3>Place An Order</h3>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.recipient_character|materializecss:'s12 m12, icon=user' }}
            </div>
            <div class="row">
                <div class="col s12 m6">
                    {{ form.ship }}
                </div>
                {{ form.quantity|materializecss:'s12 m6, icon=filter_1' }}
            </div>
            <div class="row">
                {{ form.payment_method|materializecss:'s12 m6, icon=attach_money' }}
                {{ form.notes|materializecss:'s12 m6, icon=comment' }}
                {{ form.eggs_price }}
                {{ form.isk_price }}
            </div>
            <div class="row">
                <div id="ship_info_display"></div>
            </div>
            <button class="btn waves-effect waves-light green" type="submit"
                    value="Submit" id="submit_btn">
                Go To Order Confirmation Screen
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>


{% endblock %}
{% block extrafooter %}
    {{ ship_data|json_script:"ship_data" }}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <link href="{% static 'admin/css/vendor/select2/select2.min.css' %}" type="text/css"
          media="screen" rel="stylesheet">
    <script src="{% static 'admin/js/vendor/select2/select2.full.js' %}"
            type="text/javascript"></script>

    <script>

    function numberWithCommas(x) {
        var x = x.toString()
        var x = x.replace(/,/g, '')
        return x.replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    }

    function update_select_text_with_ship_data(ship_data) {
        $("#id_ship option").each(function () {
            ship_id = $(this).val()
            ship_info = ship_data[ship_id.toString()]
            text = `${ship_info['name']} (T${ship_info.tech_level})`
            if (ship_info.free) {
                if (ship_info.blocked_until) {
                    text += " - Next Free Ship On: " + ship_info.blocked_until
                } else {
                    text += " - FREE "
                }
            }
            $(this).text(text)
        })
    }

    $(document).ready(function () {
        const ship_data = JSON.parse(document.getElementById('ship_data').textContent)
        update_select_text_with_ship_data(ship_data)
        $('#id_ship').select2()
        $('#id_ship').on('change paste keyup', function () {
            return update_after_ship_change(ship_data)
        })
        $('#id_quantity').on('change paste keyup', function () {
            return update_after_ship_change(ship_data)
        })
        $('#id_payment_method').on('change paste keyup', function () {
            return update_after_ship_change(ship_data)
        })

        update_after_ship_change(ship_data)
    })

    function update_after_ship_change(ship_data) {
        const ship_id = $('#id_ship').find('option:selected').val()
        const quantity = $('#id_quantity').val()
        current_payment = $('#id_payment_method').find('option:selected').val()
        const selectedCategory = document.querySelector('#id_payment_method')
        selected_ship_data = ship_data[ship_id.toString()]
        if (selected_ship_data) {
            $('#submit_btn').prop('disabled', false)
            paid_method = current_payment === "eggs" || current_payment === "isk"
            free_method = current_payment === "free"
            display = ""
            if (selected_ship_data.free) {
                free_option = $("#id_payment_method option[value='free']")
                if (free_option.length === 0) {
                    $('#id_payment_method').append($('<option>', {
                        value: "free",
                        text: "free"
                    }))
                    M.FormSelect.init(selectedCategory)
                }
                display = ""
                if (selected_ship_data.blocked_until && free_method) {
                    olg = selected_ship_data.order_limit_group
                    display += `<b class="orange-text">Warning: you have already ordered from the ${olg.name} category in the last ${olg.days_between_orders} days.
                If you place this order it will be blocked from starting until ${selected_ship_data.blocked_until}.</b>`
                } else if (paid_method) {
                    if (selected_ship_data.blocked_until) {
                        display += `<b class='orange-text'>Your next free ship in this category can be ordered after: ${selected_ship_data.blocked_until}.</b>
                    <br/> For now you can pay for the ship to get it quicker.`
                    } else {
                        display += "<b class='orange-text'>Warning: you are choosing to pay for this ship which you could have for free if you set the method to free!</b>"
                    }
                }
                if (free_method && quantity > 1) {
                    display = " <h4 class='red-text'>ERROR</h4><b>You cannot order more than one free ship at once. If you wish to pay for the rest make a seperate order for them.</b>"
                    $('#submit_btn').prop('disabled', true)
                }
            } else {
                $('#id_payment_method option[value="free"]').remove()
                if (current_payment === "free") {
                    current_payment = "eggs"
                    paid_method = true
                    selectedCategory.value = "eggs"
                }
                M.FormSelect.init(selectedCategory)
            }
            if (selected_ship_data.valid_price) {
                if(quantity > 1){
                    display += ` <br/> ISK PRICE: ${numberWithCommas(selected_ship_data.isk_price)} x ${quantity} = ${numberWithCommas(selected_ship_data.isk_price*quantity)}`
                    display += ` <br/> EGGS PRICE: ${numberWithCommas(selected_ship_data.eggs_price)} x ${quantity} = ${numberWithCommas(selected_ship_data.eggs_price*quantity)}`
                } else {
                    display += ` <br/> ISK PRICE: ${numberWithCommas(selected_ship_data.isk_price)}`
                    display += ` <br/> EGGS PRICE: ${numberWithCommas(selected_ship_data.eggs_price)}`
                }
            } else if (paid_method) {
                display += ` <h5 class='orange-text'>WARNING</h5> <br/> Unable to lookup a valid price for this ship from Wal Marx. {{ PRICE_CONTACT_INFO }}
                If you place this order now without a valid price the industry team will manually price your ship later on.`
            }
            if (current_payment === "srp") {
                display += "<br/><b class='red-text'>You must upload a screenshot of your lossmail to imgur and include the link in the notes.</b>"
            }
            $('#id_isk_price').val(selected_ship_data.isk_price)
            $('#id_eggs_price').val(selected_ship_data.eggs_price)
            $('#ship_info_display').html(display)
        } else {
            console.log("none?")
            $('#submit_btn').prop('disabled', true)
        }

    }


    </script>

{% endblock %}

goosetools/industry/templates/industry/shiporders/olg_edit.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>Edit Order Limit Group</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m6, icon=label' }}
                {{ form.days_between_orders|materializecss:'s12 m6, icon=person' }}
            </div>
            <div class="row">
                {{ form.ships|materializecss:'s12 m12, icon=ship' }}
            </div>

            <label>
                <button class="btn waves-effect waves-light" type="submit"
                        value="Submit">Edit
                    <i class="material-icons right">send</i>
                </button>
                <br/>
                <br/>
                <button class="btn waves-effect waves-light red" type="submit"
                        value="Delete" name="delete">Delete
                </button>
        </form>
    </div>
{% endblock %}

goosetools/industry/templates/industry/shiporders/olg_list.html
{% extends "core/base.html" %}
{% block body %}
    <div class="section">
        <h4>Order Limit Group Admin</h4>
    </div>
    <div class="section">
        <a class="waves-btn btn" href="{% url 'industry:new_olg' %}">Create New Order
            Limit Group</a>
        <ul class="collection" style="overflow: visible;">
            {% for o in olgs %}
                <li class="collection-item ">
                    <a href="{% url 'industry:edit_olg' o.id %}"
                       class="waves-btn btn secondary-content">Edit</a>
                    <span class="title"><b>{{ o.name }}</b></span>
                    </span>
                    <p>
                        Days Between Orders: {{ o.days_between_orders }}<br/>
                        Ships In Group: {{ o.ships }}
                    </p>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

goosetools/industry/templates/industry/shiporders/olg_new.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>New Order Limit Group</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m6, icon=label' }}
                {{ form.days_between_orders|materializecss:'s12 m6, icon=person' }}
            </div>
            <div class="row">
                {{ form.ships|materializecss:'s12 m12, icon=ship' }}
            </div>

            <label>
                <button class="btn waves-effect waves-light" type="submit"
                        value="Submit">Create New Group
                    <i class="material-icons right">send</i>
                </button>
        </form>
    </div>
{% endblock %}

goosetools/industry/templates/industry/shiporders/ship_dashboard.html
{% extends "core/datatable.html" %}
{% load static %}

{% block datatable_title %}
    Industry Ship Admin Dashboard
{% endblock %}
{% block datatable_top_row %}
    <a class="waves-btn btn" href="{% url 'industry:olg_list' %}">Order Limit Groups</a>
    <a class="waves-btn btn green" href="{% url 'industry:new_ship' %}">Create New
        Ship</a>
{% endblock %}

{% block datatable_footer %}
    <script src="{% static 'industry/js/ship_dashboard.js' %}"
            type="text/javascript"></script>
{% endblock %}

goosetools/industry/templates/industry/shiporders/ship_edit.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>Edit Ship</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m6, icon=label' }}
                {{ form.free|materializecss:'s12 m6, icon=person' }}
            </div>
            <div class="row">
                {{ form.tech_level|materializecss:'s12 m6, icon=label' }}
                {{ form.order_limit_group|materializecss:'s12 m6, icon=ship' }}
            </div>

            <label>
                <button class="btn waves-effect waves-light" type="submit"
                        value="Submit">Edit
                    <i class="material-icons right">send</i>
                </button>
        </form>
    </div>
{% endblock %}

goosetools/industry/templates/industry/shiporders/ship_new.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>New Ship</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m6, icon=label' }}
                {{ form.free|materializecss:'s12 m6, icon=person' }}
            </div>
            <div class="row">
                {{ form.tech_level|materializecss:'s12 m6, icon=label' }}
                {{ form.order_limit_group|materializecss:'s12 m6, icon=ship' }}
            </div>

            <label>
                <button class="btn waves-effect waves-light" type="submit"
                        value="Submit">Create New Ship
                    <i class="material-icons right">send</i>
                </button>
        </form>
    </div>
{% endblock %}