config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import re_path

urlpatterns = [
    re_path(
        r"^" + settings.URL_PREFIX,
        include(
            [
                path("admin/", admin.site.urls),
                # TODO Namespace the apps and put them on sub urls.
                path("", include("users.urls")),
                path("", include("fleets.urls")),
                path("", include("bank.urls")),
                path("", include("items.urls")),
                path("", include("contracts.urls")),
                path("", include("market.urls")),
                path("", include("ownership.urls")),
                path("", include("core.urls")),
                path(
                    "api/", include("rest_framework.urls", namespace="rest_framework")
                ),
                path("", include("django_prometheus.urls")),
                path("accounts/", include("allauth.urls")),
                path("tinymce/", include("tinymce.urls")),
                path("comments/", include("django_comments.urls")),
                path("forms/", include("user_forms.urls")),
                path("notifications/", include("notifications.urls")),
                path("hordak/", include("hordak.urls", namespace="hordak")),
                path("venmo/", include("venmo.urls")),
                path("mapbot/", include("mapbot.urls")),
                path("industry/", include("industry.urls")),
                path("pricing/", include("pricing.urls")),
            ]
            + settings.ENV_SPECIFIC_URLS
        ),
    )
]


def core_handler500(request):
    return render(request, "core/500.html", status=500)


handler500 = core_handler500

goosetools/user_forms/urls.py
from django.urls import path

from goosetools.user_forms.views import (
    FormCreate,
    FormDelete,
    FormDetail,
    FormList,
    FormUpdate,
)

app_name = "user_forms"

urlpatterns = [
    path("form/", FormList.as_view(), name="form-list"),
    path("form/<int:pk>/", FormDetail.as_view(), name="form-detail"),
    path("form/create/", FormCreate.as_view(), name="form-create"),
    path("form/<int:pk>/update", FormUpdate.as_view(), name="form-update"),
    path("form/<int:pk>/delete/", FormDelete.as_view(), name="form-delete"),
]

goosetools/user_forms/models.py
from django.db import models
from django.urls import reverse


class DynamicForm(models.Model):
    title = models.TextField()
    description = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse("user_forms:form-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.title


class FormQuestion(models.Model):
    form = models.ForeignKey(DynamicForm, on_delete=models.CASCADE)
    question_type = models.TextField(
        choices=[
            ("text", "text"),
        ],
        default="text",
    )
    title = models.TextField()
    help_text = models.TextField(null=True, blank=True)
    is_required = models.BooleanField(default=True)

goosetools/user_forms/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from goosetools.notifications.notification_types import NOTIFICATION_TYPES
from goosetools.user_forms.forms import FormQuestionFormSet, GeneratedForm
from goosetools.user_forms.models import DynamicForm


class FormList(ListView):
    queryset = DynamicForm.objects.order_by("-title")
    context_object_name = "form_list"


class FormCreate(CreateView):
    model = DynamicForm
    fields = ["title", "description"]

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["questions"] = FormQuestionFormSet(self.request.POST)
        else:
            data["questions"] = FormQuestionFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        questions = context["questions"]
        if questions.is_valid():
            response = super().form_valid(form)
            questions.instance = self.object  # type: ignore
            questions.save()
            NOTIFICATION_TYPES["no_signup_form"].dismiss()
            return response
        else:
            return super().form_invalid(form)


class FormUpdate(UpdateView):
    model = DynamicForm
    fields = ["title", "description"]

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["questions"] = FormQuestionFormSet(
                self.request.POST, instance=self.object
            )  # type: ignore
            data["questions"].full_clean()
        else:
            data["questions"] = FormQuestionFormSet(
                instance=self.object
            )  # type: ignore
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        questions = context["questions"]
        if questions.is_valid():
            response = super().form_valid(form)
            questions.instance = self.object  # type: ignore
            questions.save()
            return response
        else:
            return super().form_invalid(form)


class FormDelete(DeleteView):
    model = DynamicForm
    success_url = reverse_lazy("user_forms:form-list")


class FormDetail(DetailView):
    model = DynamicForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["form"] = GeneratedForm(self.object)  # type: ignore
        return data

goosetools/user_forms/templates/user_forms/dynamicform_confirm_delete.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>Delete Form {{ dynamicform.title }}</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% if form.non_field_errors %}
                <div class="row">
                    <div class="col s12 m5">
                        <div class="card-panel red darken-1">
                    <span class="white-text">
                        <b>Errors with form:</b>
                    <ul class="errors">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                    </span>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% csrf_token %}

            {% for field in form %}
                <div class="row">
                    {{ field|materializecss:'s12 m12' }}
                </div>
            {% endfor %}
            <button class="btn waves-effect waves-light red " type="submit"
                    value="Submit">Confirm Deleting Form
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
{% endblock %}

goosetools/user_forms/templates/user_forms/dynamicform_detail.html
{% extends "core/base.html" %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h4>Form Info: {{ dynamicform.title }}</h4>
        <a href="{% url 'user_forms:form-list' %}">Back to All Forms</a>
    </div>
    <div class="section">
        <a href="{% url 'user_forms:form-update' dynamicform.id %}"
           class="waves-btn btn">Edit Form</a>
        <a href="{% url 'user_forms:form-delete' dynamicform.id %}"
           class="waves-btn btn red">Delete Form</a>
        </span>
        <p>
            Description: {{ dynamicform.description }}<br/>
        <h5>Form Preview:</h5>
        <div class="row">
            <div class="col s12 center">
                <h1>{{ dynamicform.title }}</h1>
                <p>
                    {{ dynamicform.description|linebreaks }}
                </p>
            </div>
        </div>
        <!-- Display Form -->
        <form action="" method="post">
            {% csrf_token %}
            <ul class="collection">
                {% for field in form %}
                    <li class="collection-item">
                        <div class="row">
                            <div class="col s12">
                                {{ field|materializecss }}
                            </div>
                        </div>
                    </li>
                {% endfor %}
                <li class="collection-item center">
                    <button class="green btn waves-btn btn-large" type="submit"
                            disabled>Submit &raquo;
                    </button>
                </li>
            </ul>
        </form>
        </p>
    </div>

{% endblock %}

goosetools/user_forms/templates/user_forms/dynamicform_form.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        {% if dynamicform %}
            <h5>Edit Form: {{ dynamicform.title }}</h5>
        {% else %}
            <h5>Create New Form</h5>
        {% endif %}
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% if form.non_field_errors %}
                <div class="row">
                    <div class="col s12 m5">
                        <div class="card-panel red darken-1">
                    <span class="white-text">
                        <b>Errors with form:</b>
                    <ul class="errors">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                    </span>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% csrf_token %}

            {% for field in form %}
                <div class="row">
                    {{ field|materializecss:'s12 m12' }}
                </div>
            {% endfor %}

            {{ questions.management_form }}

            <div id="formset-wrapper">
                <div class="row">
                    <div class="col s12">
                        <h6>Form Questions</h6><br/>
                    </div>
                </div>
                <ul class="collection items">
                    {% for question_form in questions %}
                        <li class="collection-item" id="{{ question_form.prefix }}-row">
                            <div class="row">
                                {% if question_form.instance.pk %}
                                    {{ question_form.DELETE }}{% endif %}
                                {% for field in question_form %}
                                    {% if field.name == "id" or field.name == "form" %}
                                        {{ field }}
                                    {% elif field.name != "DELETE" %}
                                        {{ field|materializecss }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <li class="collection-item" id="form_template" style="display:none">
                <div class="row">
                    {% for field in questions.empty_form %}
                        {% if field.name == "id" or field.name == "form" %}
                            {{ field }}
                        {% elif field.name != "DELETE" %}
                            {{ field|materializecss }}
                        {% endif %}
                    {% endfor %}
                </div>
            </li>

            <button class="btn waves-effect waves-light" type="submit" value="Submit">
                Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
{% endblock %}
{% block extrafooter %}

    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'core/js/jquery.formset.js' %}"
            type="text/javascript"></script>

    <script>
    $(function () {
        var elems = document.querySelectorAll('#formset-wrapper select')
        var instances = M.FormSelect.init(elems)
        $('#formset-wrapper .collection-item').formset({
            formTemplate: "#form_template",
            prefix: 'formquestion_set',
            addText: 'add question',          // Text for the add link
            deleteText: 'remove',            // Text for the delete link
            addCssClass: 'waves-btn btn green',
            deleteCssClass: 'waves-btn btn red',
            added: function () {
                var elems = document.querySelectorAll('#formset-wrapper select')
                var instances = M.FormSelect.init(elems)
            }
        })

    })
    </script>


{% endblock %}
{% block initfooter %}
{% endblock %}

goosetools/user_forms/templates/user_forms/dynamicform_list.html
{% extends "core/base.html" %}
{% block body %}
    <div class="section">
        <h4>Sign Up Form Admin</h4>
        <p>Want to ask new members questions and review their answers before accepting
            them to join this site? You can do exactly that by creating a new Corp Sign
            Up form below and linking it to the corp in the <a
                    href="{% url 'corps_list' %}">Corp Admin</a>.</p>
        <a class="btn waves-btn" href="{% url "code_of_conduct_edit" %}">Edit Code of
            Conduct</a>
        <a class="waves-btn btn green" href="{% url 'user_forms:form-create' %}">Create
            New Corp Sign Up Form</a>
        <ul class="collection" style="overflow: visible;">
            {% if form_list %}
                {% for dynamicform in form_list %}
                    <li class="collection-item ">
                        <a href="{% url 'user_forms:form-update' dynamicform.id %}"
                           class="waves-btn btn secondary-content">Edit Form</a>
                        <a href="{% url 'user_forms:form-delete' dynamicform.id %}"
                           class="waves-btn btn red secondary-content">Delete Form</a>
                        <span class="title"><a
                                href="{% url 'user_forms:form-detail' dynamicform.id %}">{{ dynamicform.title }}</a>
            </span>
                        <p>
                            Description: {{ dynamicform.description }}
                        </p>
                    </li>
                {% endfor %}
            {% else %}
                <li class="collection-item"> You haven't created any Corp Sign Up Forms.
                    Click the Create button above to start a new one.
                </li>
            {% endif %}
        </ul>
    </div>

{% endblock %}