config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import re_path

urlpatterns = [
    re_path(
        r"^" + settings.URL_PREFIX,
        include(
            [
                path("admin/", admin.site.urls),
                # TODO Namespace the apps and put them on sub urls.
                path("", include("users.urls")),
                path("", include("fleets.urls")),
                path("", include("bank.urls")),
                path("", include("items.urls")),
                path("", include("contracts.urls")),
                path("", include("market.urls")),
                path("", include("ownership.urls")),
                path("", include("core.urls")),
                path(
                    "api/", include("rest_framework.urls", namespace="rest_framework")
                ),
                path("", include("django_prometheus.urls")),
                path("accounts/", include("allauth.urls")),
                path("tinymce/", include("tinymce.urls")),
                path("comments/", include("django_comments.urls")),
                path("forms/", include("user_forms.urls")),
                path("notifications/", include("notifications.urls")),
                path("hordak/", include("hordak.urls", namespace="hordak")),
                path("venmo/", include("venmo.urls")),
                path("mapbot/", include("mapbot.urls")),
                path("industry/", include("industry.urls")),
                path("pricing/", include("pricing.urls")),
            ]
            + settings.ENV_SPECIFIC_URLS
        ),
    )
]


def core_handler500(request):
    return render(request, "core/500.html", status=500)


handler500 = core_handler500

goosetools/tenants/urls.py
from django.urls import path

from goosetools.tenants.views import (
    ClientCreate,
    FirstClientCreate,
    help_page,
    login_cancelled,
    splash,
)

app_name = "tenants"

urlpatterns = [
    path("", splash, name="splash"),
    path("help", help_page, name="help"),
    path("signup", ClientCreate.as_view(), name="client-create"),
    path("setup", FirstClientCreate.as_view(), name="setup_install"),
    path("accounts/social/login/cancelled", login_cancelled, "login_cancelled"),
]

goosetools/tenants/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_tenants.models import DomainMixin, TenantMixin


class SiteUser(AbstractUser):
    username = models.CharField(
        max_length=150,
        unique=True,
        validators=[],
        error_messages={"unique": _("A user with that username already exists.")},
    )

    def has_gooseuser(self):
        return hasattr(self, "gooseuser")

    def is_approved(self):
        # pylint: disable=no-member
        return self.has_gooseuser() and self.gooseuser.is_approved()

    def is_rejected(self):
        # pylint: disable=no-member
        return self.has_gooseuser() and self.gooseuser.is_rejected()

    def discord_socialaccount(self):
        return self.socialaccount_set.get(provider="discord")

    @staticmethod
    def create(username):
        site_user = SiteUser(
            first_name="",
            last_name="",
            email="",
            password="",
            username=username,
            is_staff=False,
            is_active=True,
            date_joined=timezone.now(),
            is_superuser=False,
        )
        site_user.save()
        return site_user

    @staticmethod
    def copy_from_user(user):
        site_user, _ = SiteUser.objects.update_or_create(
            username=user.username,
            defaults={
                "is_staff": user.is_staff,
                "is_active": user.is_active,
                "date_joined": user.date_joined,
                "password": user.password or "",
                "last_login": user.last_login,
                "is_superuser": user.is_superuser,
                "first_name": user.first_name or "",
                "last_name": user.last_name or "",
                "email": user.email or "",
            },
        )
        user.site_user_id = site_user.id
        user.save()
        return site_user


class Client(TenantMixin):
    name = models.CharField(
        max_length=100,
        help_text="The name of your organization.",
        validators=[RegexValidator("^[a-z0-9_]{1,100}$")],
    )
    owner = models.ForeignKey(
        SiteUser, on_delete=models.SET_NULL, null=True, blank=True
    )
    paid_until = models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)

    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True


class Domain(DomainMixin):
    pass

goosetools/tenants/forms.py
from django import forms

from goosetools.tenants.models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ("name",)

goosetools/tenants/views.py
from allauth.socialaccount.models import SocialApp
from django.conf import settings
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.utils import timezone
from django.views.generic.edit import CreateView
from django_tenants.utils import tenant_context

from goosetools.tenants.forms import ClientForm
from goosetools.tenants.models import Client, Domain
from goosetools.users.forms import SignupFormWithTimezone
from goosetools.users.handlers import setup_tenant
from goosetools.users.models import GooseUser


def _is_spacepaperwork_in_local_only_mode():
    return settings.STUB_DISCORD


def _is_spacepaperwork_setup():
    if not SocialApp.objects.exists():
        return False
    else:
        return (
            not settings.SINGLE_TENANT or Client.objects.exclude(name="public").exists()
        )


def redirect_single_tenant(f):
    def _wrapped_view(request, *args, **kwargs):
        if settings.SINGLE_TENANT:
            if Client.objects.exclude(name="public").exists():
                return HttpResponseRedirect(reverse("core:splash"))
            else:
                return HttpResponseRedirect(reverse("tenants:setup_install"))
        else:
            return f(request, *args, **kwargs)

    return _wrapped_view


def find_tenants_for_user(request, excluding=None):
    owners_orgs = []
    member_orgs = []
    if excluding:
        qs = Client.objects.exclude(id=excluding.id).all()
    else:
        qs = Client.objects.all()
    for tenant in qs:
        if tenant.name != "public" and request.user.is_authenticated:
            with tenant_context(tenant):
                if tenant.owner == request.user:
                    owners_orgs.append(tenant)
                elif GooseUser.objects.filter(site_user=request.user).count() > 0:
                    member_orgs.append(tenant)
    return owners_orgs, member_orgs


def _single_tenant_missing():
    return settings.SINGLE_TENANT and not Client.objects.exclude(name="public").exists()


class FirstClientCreate(CreateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self) -> str:
        return (
            settings.URL_PREFIX
            + "/"
            + settings.TENANT_SUBFOLDER_PREFIX
            + "/"
            + self.object.name
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["signup_form"] = SignupFormWithTimezone(self.request.POST)
        else:
            data["signup_form"] = SignupFormWithTimezone()
        return data

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        owner_orgs, _ = find_tenants_for_user(self.request)
        if len(owner_orgs) == 0:
            return super().get(request, args, kwargs)
        else:
            messages.error(
                self.request,
                f"You already own the {settings.SITE_NAME} organization '{owner_orgs[0].name}' and cannot create another.",
            )
            return HttpResponseRedirect(reverse("tenants:splash"))

    def post(self, request, *args, **kwargs):
        owner_orgs, _ = find_tenants_for_user(self.request)
        if len(owner_orgs) == 0:
            return super().post(request, *args, **kwargs)
        else:
            messages.error(
                self.request,
                f"You already own the {settings.SITE_NAME} organization '{owner_orgs[0].name}' and cannot create another.",
            )
            return HttpResponseRedirect(reverse("tenants:splash"))

    def form_valid(self, form):
        context = self.get_context_data()
        signup_form = context["signup_form"]
        if signup_form.is_valid():
            two_weeks_from_now = timezone.now() + timezone.timedelta(days=14)
            form.instance.on_trial = True
            form.instance.paid_until = two_weeks_from_now
            form.instance.owner = self.request.user
            form.instance.schema_name = form.instance.name
            r = super().form_valid(form)
            if form.is_valid():
                Domain.objects.create(
                    domain=self.object.name, is_primary=False, tenant=self.object
                )
                setup_tenant(self.object, self.request.user, signup_form.cleaned_data)
                return r
        return super().form_invalid(form)


class ClientCreate(CreateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self) -> str:
        return (
            settings.URL_PREFIX
            + "/"
            + settings.TENANT_SUBFOLDER_PREFIX
            + "/"
            + self.object.name
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["signup_form"] = SignupFormWithTimezone(self.request.POST)
        else:
            data["signup_form"] = SignupFormWithTimezone()
        return data

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        owner_orgs, _ = find_tenants_for_user(self.request)
        if len(owner_orgs) == 0:
            return super().get(request, args, kwargs)
        else:
            messages.error(
                self.request,
                f"You already own the {settings.SITE_NAME} organization '{owner_orgs[0].name}' and cannot create another.",
            )
            return HttpResponseRedirect(reverse("tenants:splash"))

    def post(self, request, *args, **kwargs):
        owner_orgs, _ = find_tenants_for_user(self.request)
        if len(owner_orgs) == 0:
            return super().post(request, *args, **kwargs)
        else:
            messages.error(
                self.request,
                f"You already own the {settings.SITE_NAME} organization '{owner_orgs[0].name}' and cannot create another.",
            )
            return HttpResponseRedirect(reverse("tenants:splash"))

    def form_valid(self, form):
        context = self.get_context_data()
        signup_form = context["signup_form"]
        if signup_form.is_valid():
            two_weeks_from_now = timezone.now() + timezone.timedelta(days=14)
            form.instance.on_trial = True
            form.instance.paid_until = two_weeks_from_now
            form.instance.owner = self.request.user
            form.instance.schema_name = form.instance.name
            r = super().form_valid(form)
            if form.is_valid():
                Domain.objects.create(
                    domain=self.object.name, is_primary=False, tenant=self.object
                )
                setup_tenant(self.object, self.request.user, signup_form.cleaned_data)
                return r
        return super().form_invalid(form)


@redirect_single_tenant
def splash(request):
    owner_orgs, member_orgs = find_tenants_for_user(request)
    return render(
        request,
        "tenants/splash.html",
        {
            "tenant_subfolder_prefix": settings.TENANT_SUBFOLDER_PREFIX,
            "owner_orgs": owner_orgs,
            "member_orgs": member_orgs,
            "orgs": owner_orgs + member_orgs,
        },
    )


@redirect_single_tenant
def help_page(request):
    owner_orgs, member_orgs = find_tenants_for_user(request)
    return render(
        request,
        "tenants/help.html",
        {
            "tenant_subfolder_prefix": settings.TENANT_SUBFOLDER_PREFIX,
            "owner_orgs": owner_orgs,
            "member_orgs": member_orgs,
            "orgs": owner_orgs + member_orgs,
        },
    )


def login_cancelled(request):
    messages.error(
        request,
        f"Sorry you cannot Login without Discord. {settings.SITE_NAME} authenticates who you are using Discord. We only request the minimum amount of data from Discord which is your username and avatar. This way is more secure for everybody as we do not need to store personal data about you such as having you enter a password and email address.",
    )
    return HttpResponseRedirect(reverse("tenants:splash"))

goosetools/tenants/templates/tenants/client_form.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        <h5>Sign Up for SpacePaperwork</h5>
        <div class="col s12 s12">
            <div class="col s12">
                <div class="card-panel">
                    <span class="card-title"><i
                            class="material-icons medium green-text">check</i>{{ SITE_NAME }} is Free!</span><br/><br/>
                    {{ SITE_NAME }} is open source free software! See our <a
                        href="https://github.com/nigel-gott/spacepaperwork">Github</a>
                    repository for all of the code so you can host your own version!
                </div>
            </div>
        </div>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% if form.non_field_errors or signup_form.non_field_errors %}
                <div class="row">
                    <div class="col s12 m5">
                        <div class="card-panel red darken-1">
                    <span class="white-text">
                        <b>Errors with form:</b>
                    <ul class="errors">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                        {% for error in signup_form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                    </span>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% csrf_token %}

            <div class="row">
                <p id="org_link"></p>
            </div>
            {% for field in form %}
                <div class="row">
                    {{ field|materializecss:'s12 m12' }}
                </div>
            {% endfor %}
            {% for field in signup_form %}
                <div class="row">
                    {{ field|materializecss:'s12 m12' }}
                </div>
            {% endfor %}

            <button id="submit_btn" class="btn waves-effect waves-light" type="submit"
                    value="Submit">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
{% endblock %}

{% block extrafooter %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <link href="{% static 'admin/css/vendor/select2/select2.min.css' %}" type="text/css"
          media="screen" rel="stylesheet">
    <script src="{% static 'admin/js/vendor/select2/select2.full.js' %}"
            type="text/javascript"></script>
    <script>
    $(document).ready(function () {
        $('#id_timezone').select2()

        function valid_name(name) {
            return /^[a-z0-9_]{1,100}$/.test(name)

        }

        function update_org_url() {
            console.log(this.value)
            name = this.value
            if (name) {
                if (valid_name(name)) {
                    $("#org_link").html(`Your SpacePaperwork Organization will be accessible at: <a href="#">https://www.spacepaperwork.com/t/${name}</a>`)
                    $("#submit_btn").prop('disabled', false)
                } else {
                    $("#org_link").html("Please enter a valid organization name. It must be <b class='red-text'>all lowercase, contain no spaces and no special characters other than numbers or underscores.</b>")
                    $("#submit_btn").prop('disabled', true)
                }
            } else {
                $("#org_link").html("<b class='red-text'>Please enter an organization name.</b>")
                $("#submit_btn").prop('disabled', true)
            }
        }

        $("#id_name").on("change paste keyup", update_org_url).trigger("change")

    })
    </script>

{% endblock %}

goosetools/tenants/templates/tenants/help.html
{% extends "tenants/public_base.html" %}
{% load static %}
{% block title %}Help | {{ SITE_NAME }}{% endblock %}
{% block body %}
    <div class="section">
        <div class="row">
            <div class="col s12 s12">
                <div class="col s12">
                    <div class="card-panel">
                        <span class="card-title">  <i
                                class="material-icons medium">help</i> Need Help with {{ SITE_NAME }}?</span>
                        Join the Discord Server below and ping @thejanitor for help.</p>

                        <div class="card-action">
                            <a href="https://discord.gg/tsHP3XStQm"
                               class="btn waves-btn">Join the {{ SITE_NAME }}
                                Discord</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

goosetools/tenants/templates/tenants/public_base.html
{% extends "core/base.html" %}
{% block title %}{{ SITE_NAME }}{% endblock %}
{% block extranavbar %}
    <li>
        {% if not orgs %}
            <a class="waves-btn btn green" href="{% url 'tenants:client-create' %}">Sign
                Up</a><br/>
        {% elif not owner_orgs %}
            <a class="waves-btn btn green" href="{% url 'tenants:client-create' %}">Create
                Site</a><br/>
        {% endif %}
    </li>
    {% if orgs %}
        {% if orgs|length == 1 %}
            <li>
                {% for org in orgs %}
                    <a class="waves-btn btn"
                       href="/{{ tenant_subfolder_prefix }}/{{ org.name }}">Go
                        To {{ org.name }}</a>
                {% endfor %}
            </li>
        {% else %}
            <li>
                <a class="dropdown-trigger valign-wrapper" data-target="dropdown_orgs"
                   href="#!">
                    <i class="material-icons left">public</i>Your Orgs</span>
                </a>
            </li>
            <ul class="dropdown-content" id="dropdown_orgs">
                {% for org in orgs %}
                    <li>
                        <a href="/{{ tenant_subfolder_prefix }}/{{ org.name }}">{{ org.name }}</a>
                    </li>
                {% endfor %}
            </ul>

        {% endif %}
    {% endif %}
{% endblock %}

goosetools/tenants/templates/tenants/splash.html
{% extends "tenants/public_base.html" %}
{% load static %}
{% block title %}{{ SITE_NAME }}{% endblock %}
{% block extraheader %}
    <link rel="stylesheet" type="text/css"
          href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <script type="text/javascript"
            src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
{% endblock %}
{% block body %}
    <div class="section">
        <div class="row">
            <div class="col s12 m12">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title orange-text">Swamped by spreadsheets in your favourite space MMORPG?</span>
                        Let <b>SpacePaperwork.com</b> do all the tedious work for you
                        and get back to exploding spaceships. <br/>
                        <br/>
                        SpacePaperwork lets you create a secure sandboxed site, which is
                        packed full of useful time-saving features, for you and all of
                        your corp mates.
                        <b>Spacepaperwork is free and open source.</b> See our <a
                            href="https://github.com/nigel-gott/spacepaperwork">Github</a>
                        repository for all of the code so you can host your own version!
                    </div>
                    <div class="card-action">
                        {% if not owner_orgs %}
                            <a class="waves-btn btn green"
                               href="{% url 'tenants:client-create' %}">Create
                                your {{ SITE_NAME }} site</a><br/>
                        {% else %}
                            {% if orgs|length == 1 %}
                                {% for org in orgs %}
                                    <a class="waves-btn btn"
                                       href="/{{ tenant_subfolder_prefix }}/{{ org.name }}">Go
                                        To {{ org.name }}</a>
                                {% endfor %}
                            {% else %}
                                <a class="dropdown-trigger valign-wrapper white-text"
                                   data-target="dropdown_orgs" href="#!">
                                    <i class="material-icons left">public</i>Your
                                    Orgs</span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="divider row"></div>
        <div class="row">
            <div class="col s12 m6">
                <h3>Loot Tracking, Selling and Profit Shares</h3>
                <ul class="browser-default splash-list splash-list">
                    <li>Easily track loot and split the profit between participants
                        using shares
                    </li>
                    <li>Manually give out loot shares or generate share links to send to
                        fleet members
                    </li>
                    <li>Stack loot together and bulk send it to sellers</li>
                    <li>Track market orders and auto calculate fees so only net profit
                        is shared out
                    </li>
                    <li>Instantly bulk buy loot or junk cheap loot based off estimate
                        prices
                    </li>
                    <li>Transfer profit using contracts or the bundled virtual corp
                        currency system
                    </li>
                    <li>Use auto-complete fields and filters to rapidly enter loot
                        without error
                    </li>
                </ul>
            </div>
            <div class="col s12 m6 custom_slick_container">
                <div class="slick">
                    <img class="responsive-img" src="{% static "tenants/1.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/2.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/3.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/4.png" %}"/>
                </div>
                <div class="button_container center"></div>
            </div>
        </div>
        <div class="divider row"></div>
        <div class="row">
            <div class="col s12 m6">
                <h3>Virtual Corp Wallet Based Currency</h3>
                <ul class="browser-default splash-list splash-list">
                    <li>Completely avoid in-game taxes by using the space paperwork corp
                        wallet virtual currency system
                    </li>
                    <li>Donate isk into a corp wallet at 0% tax in exchange for your
                        virtual corp currency
                    </li>
                    <li>Then in SpacePaperwork transfer money without paying the in-game
                        contract tax
                    </li>
                    <li>Track, audit, export, import and reconciliate user transactions
                        against the corp wallet
                    </li>
                    <li>Admins approve deposits and withdrawals into the system</li>
                </ul>
            </div>
            <div class="col s12 m6 custom_slick_container">
                <div class="slick">
                    <img class="responsive-img" src="{% static "tenants/5.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/13.png" %}"/>
                </div>
                <div class="button_container center"></div>
            </div>
        </div>
        <div class="divider row"></div>
        <div class="row">
            <div class="col s12 m6">
                <h3>Manage and track Corps and their Members</h3>
                <ul class="browser-default splash-list">
                    <li>Create Corps each with its own customizable user application
                        process
                    </li>
                    <li>Restrict access to corps based on discord roles or make them
                        fully public
                    </li>
                    <li>Corp admins approve or deny applications into SpacePaperwork
                        corps
                    </li>
                    <li>Give out discord roles on application approval</li>
                    <li>Track which users own which ALTs, what corps they are in and let
                        admins keep notes and comments on them
                    </li>
                </ul>
            </div>
            <div class="col s12 m6 custom_slick_container">
                <div class="slick">
                    <img class="responsive-img" src="{% static "tenants/6.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/7.png" %}"/>
                </div>
                <div class="button_container center"></div>
            </div>
        </div>
        <div class="divider row"></div>
        <div class="row">
            <div class="col s12 m6">
                <h3>Integrate with your Discord Server</h3>
                <ul class="browser-default splash-list">
                    <li>Connect your discord server and control all permissions using
                        roles you already have
                    </li>
                    <li>Define custom user groups and give out permissions either
                        manually or based on discord roles
                    </li>
                    <li>Easily audit corp members against who has roles in your discord
                        server or has left the server
                    </li>
                </ul>
            </div>
            <div class="col s12 m6 custom_slick_container">
                <div class="slick">
                    <img class="responsive-img" src="{% static "tenants/9.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/10.png" %}"/>
                </div>
                <div class="button_container center"></div>
            </div>
        </div>
        <div class="divider row"></div>
        <div class="row">
            <div class="col s12 m6">
                <h3>Features coming soon</h3>
                <ul class="browser-default splash-list">
                    <li>Allow users to place ship and item orders which industrialists
                        can claim and work on based off your own custom prices
                    </li>
                    <li>Give users an allowance of free ships they can order entirely
                        controlled by you
                    </li>
                    <li>Sell and buy loot, ships, items and services on internal market
                        places avoiding in-game tax entirely
                    </li>
                    <li>Place automatic buy orders letting you instantly buy loot
                        entered by ratting fleets
                    </li>
                    <li>Custom integrations or features on a per alliance basis are
                        available.
                    </li>
                </ul>
            </div>
            <div class="col s12 m6 custom_slick_container">
                <div class="slick">
                    <img class="responsive-img" src="{% static "tenants/11.png" %}"/>
                    <img class="responsive-img" src="{% static "tenants/12.png" %}"/>
                </div>
                <div class="button_container center"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extrafooter %}
    <script type="text/javascript">
    $(document).ready(function () {
        $('.custom_slick_container').each(function () {
            console.log($(this).find('.button_container'))
            $(this).find('.slick').slick({
                speed: 200,
                slidesToShow: 1,
                appendArrows: $(this).find('.button_container'),
                prevArrow: '<a class="a-left control-c prev slick-prev" href="#""><i class="medium material-icons">navigate_before</i></a>',
                nextArrow: "<a class='a-right control-c next slick-next' href='#'><i class='medium material-icons'>navigate_next</i></a>",
            })
        })
    })
    </script>
{% endblock %}