config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import re_path

urlpatterns = [
    re_path(
        r"^" + settings.URL_PREFIX,
        include(
            [
                path("admin/", admin.site.urls),
                # TODO Namespace the apps and put them on sub urls.
                path("", include("users.urls")),
                path("", include("fleets.urls")),
                path("", include("bank.urls")),
                path("", include("items.urls")),
                path("", include("contracts.urls")),
                path("", include("market.urls")),
                path("", include("ownership.urls")),
                path("", include("core.urls")),
                path(
                    "api/", include("rest_framework.urls", namespace="rest_framework")
                ),
                path("", include("django_prometheus.urls")),
                path("accounts/", include("allauth.urls")),
                path("tinymce/", include("tinymce.urls")),
                path("comments/", include("django_comments.urls")),
                path("forms/", include("user_forms.urls")),
                path("notifications/", include("notifications.urls")),
                path("hordak/", include("hordak.urls", namespace="hordak")),
                path("venmo/", include("venmo.urls")),
                path("mapbot/", include("mapbot.urls")),
                path("industry/", include("industry.urls")),
                path("pricing/", include("pricing.urls")),
            ]
            + settings.ENV_SPECIFIC_URLS
        ),
    )
]


def core_handler500(request):
    return render(request, "core/500.html", status=500)


handler500 = core_handler500

goosetools/users/urls.py
from django.urls import path
from django.urls.conf import include
from rest_framework import routers

from goosetools.users.autocomplete import (
    CharacterAutocomplete,
    UserCharacterAutocomplete,
    UsernameAutocomplete,
)
from goosetools.users.views import (
    CharacterQuerySet,
    GooseUserQuerySet,
    admin_character_edit,
    application_update,
    character_dashboard,
    character_edit,
    character_list,
    character_new,
    character_search,
    check_discord_status,
    code_of_conduct_edit,
    corp_application_list,
    corp_application_update,
    corp_select,
    corps_list,
    discord_settings,
    edit_corp,
    edit_group,
    groups_view,
    new_corp,
    new_group,
    refresh_discord_groups,
    settings_view,
    user_admin_view,
    user_application_list,
    user_dashboard,
    user_signup,
    user_view,
)

router = routers.DefaultRouter()
router.register(r"gooseuser", GooseUserQuerySet)
router.register(r"character", CharacterQuerySet)

urlpatterns = [
    path("code_of_conduct/edit", code_of_conduct_edit, name="code_of_conduct_edit"),
    path("settings/discord/check", check_discord_status, name="check_discord_status"),
    path("settings/discord", discord_settings, name="discord_settings"),
    path("settings/", settings_view, name="settings"),
    path("user/dashboard", user_dashboard, name="user_dashboard"),
    path("character/dashboard", character_dashboard, name="character_dashboard"),
    path("user/<int:pk>", user_view, name="user_view"),
    path("user/<int:pk>/admin", user_admin_view, name="user_admin_view"),
    path(
        "characters/edit/<int:pk>/admin",
        admin_character_edit,
        name="admin_character_edit",
    ),
    path("characters/edit/<int:pk>", character_edit, name="character_edit"),
    path("corp/select/", corp_select, name="corp_select"),
    path("corp/<int:pk>/apply/", user_signup, name="user_signup"),
    path("characters/new/", character_new, name="character_new"),
    path("characters/", character_list, name="characters"),
    path("characters/search", character_search, name="character_search"),
    path("applications/", user_application_list, name="applications"),
    path("applications/corp", corp_application_list, name="corp_applications"),
    path(
        "applications/update/<int:pk>/", application_update, name="application_update"
    ),
    path(
        "applications/update/corp/<int:pk>/",
        corp_application_update,
        name="corp_application_update",
    ),
    path(
        r"character-autocomplete/",
        CharacterAutocomplete.as_view(),
        name="character-autocomplete",
    ),
    path(
        r"user-character-autocomplete/",
        UserCharacterAutocomplete.as_view(),
        name="user-character-autocomplete",
    ),
    path(
        r"username-autocomplete/",
        UsernameAutocomplete.as_view(),
        name="username-autocomplete",
    ),
    path("api/", include(router.urls)),
    path("corps/", corps_list, name="corps_list"),
    path("corps/<int:pk>/edit", edit_corp, name="edit_corp"),
    path("corps/new", new_corp, name="new_corp"),
    path("groups/", groups_view, name="groups_view"),
    path("groups/<int:pk>/edit", edit_group, name="edit_group"),
    path("groups/new", new_group, name="new_group"),
    path(
        "groups/refresh_discord", refresh_discord_groups, name="refresh_discord_groups"
    ),
]

goosetools/users/models.py
import logging
from functools import partial, wraps
from typing import List, Union

import requests
from django.conf import settings
from django.contrib.postgres.aggregates.general import StringAgg
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.db import models
from django.http.response import HttpResponseForbidden
from django.utils import timezone
from django_comments.models import Comment
from requests.exceptions import RequestException
from rest_framework.permissions import BasePermission
from timezone_field import TimeZoneField

from goosetools.notifications.notification_types import NOTIFICATION_TYPES
from goosetools.tenants.models import SiteUser
from goosetools.user_forms.models import DynamicForm

logger = logging.getLogger(__name__)


class AuthConfig(models.Model):
    active = models.BooleanField(default=True)
    code_of_conduct = models.TextField(null=True, blank=True)

    # pylint: disable=signature-differs
    def save(self, *args, **kwargs):
        if self.active:
            try:
                other_active = AuthConfig.objects.get(active=True)
                if self != other_active:
                    other_active.active = False
                    other_active.save()
            except AuthConfig.DoesNotExist:
                pass
        super().save(*args, **kwargs)

    @staticmethod
    def get_active():
        return AuthConfig.objects.get(active=True)

    @staticmethod
    def ensure_exists():
        if AuthConfig.objects.filter(active=True).count() == 0:
            AuthConfig.objects.create(
                active=True,
            )


MANAGE_ROLES_DISCORD_PERMISSION = 0x10000000


class DiscordGuild(models.Model):
    guild_id = models.TextField(null=True, blank=True)
    server_name = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=False)
    connection_valid = models.BooleanField(default=False)
    discord_connection_issue = models.BooleanField(default=False)
    has_manage_roles = models.BooleanField(default=False)

    @staticmethod
    def bot_headers():
        return {
            "Authorization": "Bot {0}".format(settings.BOT_TOKEN),
        }

    def _check_discord_is_up_and_bot_valid(self):
        self.discord_connection_issue = False
        url = "https://discord.com/api/users/@me"
        try:
            bot_info_request = requests.get(url, headers=DiscordGuild.bot_headers())
            bot_info_request.raise_for_status()
        except RequestException as e:
            logger.info("Error querying discord for bot info: " + str(e))
            self.discord_connection_issue = True
            return False
        bot_info = bot_info_request.json()
        if "id" not in bot_info or not bot_info["bot"]:
            logger.info("Missing Id from bot info request: " + bot_info_request.text)
            self.discord_connection_issue = True
            return False
        return True

    def _check_for_permissions(self):
        self.has_manage_roles = False
        url = f"https://discord.com/api/guilds/{self.guild_id}/members/{settings.BOT_USER_ID}"
        try:
            bot_member_request = requests.get(url, headers=DiscordGuild.bot_headers())
            bot_member_request.raise_for_status()
        except RequestException as e:
            logger.info("Error querying discord for member info: " + str(e))
        bot_member_info = bot_member_request.json()
        if "roles" not in bot_member_info:
            logger.info(
                "Missing roles discord bot info request: " + bot_member_request.text
            )
        else:
            try:
                url = f"https://discord.com/api/guilds/{self.guild_id}/roles"
                try:
                    roles_request = requests.get(
                        url, headers=DiscordGuild.bot_headers()
                    )
                    roles_request.raise_for_status()
                except RequestException as e:
                    logger.info("Error querying discord for roles info: " + str(e))

                roles_by_id = {role["id"]: role for role in roles_request.json()}

                for role in bot_member_info["roles"]:
                    permissions = int(roles_by_id[role]["permissions"])
                    self.has_manage_roles = (
                        permissions & MANAGE_ROLES_DISCORD_PERMISSION
                    ) == MANAGE_ROLES_DISCORD_PERMISSION
                    if self.has_manage_roles:
                        return
            except (ValueError, KeyError):
                logger.info(
                    "Weird permissions from discord guild:" + bot_member_request.text
                )
                if roles_request and hasattr(roles_request, "text"):
                    logger.info(roles_request.text)

    def _check_discord_guild_is_valid(self):
        self.server_name = None
        url = f"https://discord.com/api/guilds/{self.guild_id}"
        try:
            guild_info_request = requests.get(url, headers=DiscordGuild.bot_headers())
            guild_info_request.raise_for_status()
        except RequestException as e:
            logger.error("Error querying discord for guild info: " + str(e))
            return False
        guild_info = guild_info_request.json()
        if "name" not in guild_info:
            logger.info(
                "Missing Name from discord guild info request: "
                + guild_info_request.text
            )
            return False
        else:
            self.server_name = guild_info["name"]

        return True

    def _update_status_fields(self):
        self.connection_valid = False
        if self.guild_id:
            if (
                self._check_discord_is_up_and_bot_valid()
                and self._check_discord_guild_is_valid()
            ):
                self._check_for_permissions()
                self.connection_valid = True

    def check_valid(self):
        self._update_status_fields()
        self.save()
        if self.connection_valid:
            DiscordRole.sync_from_discord()
            NOTIFICATION_TYPES["discord_not_setup"].dismiss()
        else:
            NOTIFICATION_TYPES["discord_not_setup"].send()
        return self.connection_valid

    @staticmethod
    def try_give_role(uid, role_id):
        try:
            guild = DiscordGuild.objects.get(active=True)
            bot_headers = {
                "Authorization": "Bot {0}".format(settings.BOT_TOKEN),
            }
            url = f"https://discord.com/api/guilds/{guild.guild_id}/members/{uid}/roles/{role_id}"
            request = requests.put(url, headers=bot_headers)
            request.raise_for_status()
        except DiscordGuild.DoesNotExist:
            pass

    @staticmethod
    def get_roles():
        try:
            guild = DiscordGuild.objects.get(active=True)
            bot_headers = {
                "Authorization": "Bot {0}".format(settings.BOT_TOKEN),
            }
            url = f"https://discord.com/api/guilds/{guild.guild_id}"
            request = requests.get(url, headers=bot_headers)
            request.raise_for_status()
            return [(role["name"], role["id"]) for role in request.json()["roles"]]
        except DiscordGuild.DoesNotExist:
            return []

    @staticmethod
    def get_active():
        try:
            return DiscordGuild.objects.get(active=True)
        except DiscordGuild.DoesNotExist:
            return False

    # pylint: disable=signature-differs
    def save(self, *args, **kwargs):
        if self.active:
            try:
                other_active = DiscordGuild.objects.get(active=True)
                if self != other_active:
                    other_active.active = False
                    other_active.save()
            except DiscordGuild.DoesNotExist:
                pass
        super().save(*args, **kwargs)


class DiscordRole(models.Model):
    name = models.TextField()
    role_id = models.TextField(unique=True)

    def __str__(self) -> str:
        return self.name

    @staticmethod
    def sync_from_discord():
        if not settings.STUB_DISCORD:
            all_ids = set()
            for role_name, role_id in DiscordGuild.get_roles():
                all_ids.add(role_id)
                DiscordRole.objects.update_or_create(
                    role_id=role_id, defaults={"name": role_name}
                )

            DiscordRole.objects.exclude(role_id__in=all_ids).delete()

    class Meta:
        indexes = [
            models.Index(fields=["name"]),
        ]


class GooseGroup(models.Model):
    name = models.TextField(unique=True)
    description = models.TextField()
    editable = models.BooleanField(default=True)
    manually_given = models.BooleanField(default=False)
    linked_discord_role = models.TextField(null=True, blank=True)
    required_discord_role = models.ForeignKey(
        DiscordRole, on_delete=models.SET_NULL, null=True, blank=True
    )

    def link_permission(self, permission_name: str):
        perm, _ = GoosePermission.objects.get_or_create(name=permission_name)
        GroupPermission.objects.get_or_create(group=self, permission_id=perm.id)

    def permissions(self):
        return list(
            GoosePermission.objects.filter(grouppermission__group=self)
            .all()
            .values_list("name", flat=True)
        )

    def __str__(self) -> str:
        return f"{self.name}"

    @staticmethod
    def superuser_group():
        return GooseGroup.objects.get(name=SUPERUSER_GROUP_NAME)


class Corp(models.Model):
    name = models.TextField(unique=True)
    full_name = models.TextField(unique=True, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    auto_approve = models.BooleanField(default=False)
    public_corp = models.BooleanField(default=False)
    editable = models.BooleanField(default=True)
    sign_up_form = models.ForeignKey(
        DynamicForm,

goosetools/users/templates/users/admin_character_edit.html
{% extends "core/base.html" %}
{% load static %}
{% load materializecss %}
{% block body %}
    <div class="section">
        <h5>Admin Edit Character</h5>
    </div>
    <div class="divider"></div>
    {% if form %}
        <!-- Form Errors -->
        {% if form.non_field_errors %}
            <div class="row">
                <div class="col s12 m5">
                    <div class="card-panel red darken-1">
                <span class="white-text">
                    <b>Errors with form:</b>
                <ul class="errors">
                    {% for error in form.non_field_errors %}
                        <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                </span>
                    </div>
                </div>
            </div>
        {% endif %}

        <!-- Display Form -->
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">

                <div class="col m2 m2">
                    User who Owns this Character:
                </div>
                <div class="col m10 m10">
                    {{ form.gooseuser|materializecss:'s12 m12, icon=user' }}
                </div>
            </div>
            <div class="row">
                <div class="col m2 m2">
                    The Characters In-Game Name:
                </div>
                <div class="col m10 m10">
                    {{ form.ingame_name|materializecss:'s12 m12, icon=user' }}
                </div>
            </div>
            <div class="row">
                <div class="col m2 m2">
                    The Characters In-Game Corp:
                </div>
                <div class="col m10 m10">
                    {{ form.corp|materializecss:'s12 m12, icon=user' }}
                </div>
            </div>
            <br/>
            <button type="submit" class="btn waves-effect waves-light" value="Submit">
                Edit Character
                <i class="material-icons right">send</i>
            </button>
        </form>
    {% endif %}
    </div>


{% endblock %}

{% block extrafooter %}
    <script type="text/javascript"
            src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {{ form.media }}
    </script>
{% endblock %}

goosetools/users/templates/users/character_dashboard.html
{% extends "core/datatable.html" %}
{% load static %}

{% block datatable_title %}
    Character Dashboard
{% endblock %}

{% block datatable_footer %}
    <script src="{% static 'users/js/character_dashboard.js' %}"
            type="text/javascript"></script>
{% endblock %}

goosetools/users/templates/users/character_new.html
{% extends "core/base.html" %}
{% block body %}
    <div class="section">
        <h5>New Character</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="row">
                    <div class="input-field col s12">
                        {{ field.errors }}
                        {{ field }}
                        {{ field.label_tag }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </div>

            {% endfor %}
            <label>
                <button class="btn waves-effect waves-light" type="submit"
                        value="Submit">Submit Change Request
                    <i class="material-icons right">send</i>
                </button>
        </form>
    </div>
{% endblock %}

goosetools/users/templates/users/code_of_conduct_edit.html
{% extends "core/base.html" %}

{% block body %}
    <div class="section">
        <h5>Change your Code of Conduct</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="row">
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                    <div class="input-field col s12">
                        {{ field.errors }}
                        {{ field }}
                        {{ field.label_tag }}
                    </div>
                </div>

            {% endfor %}
            <button class="btn waves-effect waves-light" type="submit" value="Submit">
                Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
{% endblock %}

{% block extraheader %}
    {{ form.media }}
{% endblock %}

goosetools/users/templates/users/corp_select.html
{% extends "core/base.html" %}

{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% trans "Corp Select" %}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col s12">
            <h1>{% trans "Select the Corp you wish to apply to" %}</h1>
            <ul class="collection">
                {% for corp in corps %}
                    <li class="collection-item">
                        <span class="title">{{ corp.name_with_corp_tag }}</span>

                        <p>
                            {% if corp.description %}
                                {{ corp.description }}<br/></br>
                            {% endif %}
                            <a href="{% url 'user_signup' corp.id %}"
                               class="btn waves-btn">Apply</a><br/>
                        </p>

                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

goosetools/users/templates/users/edit_group.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        <h5>Edit User Group</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <!-- Form Errors -->
        {% if form.non_field_errors %}
            <div class="row">
                <div class="col s12 m5">
                    <div class="card-panel red darken-1">
                <span class="white-text">
                    <b>Errors with form:</b>
                <ul class="errors">
                    {% for error in form.non_field_errors %}
                        <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                </span>
                    </div>
                </div>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.description|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.manually_given|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row" id="role_id">
                {{ form.required_discord_role_id|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.permissions|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <button class="btn waves-effect waves-light" type="submit" value="Submit">
                Submit Changes
                <i class="material-icons right">send</i>
            </button>
            <br/>
            <br/>
            <button class="btn waves-effect waves-light red" type="submit"
                    value="Delete" name="delete">Delete Group
            </button>
        </form>
    </div>
{% endblock %}
{% block extrafooter %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <script>
    $(document).ready(function () {
        function hide_roles_if_manually_given() {
            if (this.checked) {
                $("#role_id").hide()
            } else {
                $("#role_id").show()
            }
        }

        $("#id_manually_given").on("change", hide_roles_if_manually_given).trigger("change")

    })
    </script>

{% endblock %}

goosetools/users/templates/users/new_character.html
{% extends "core/base.html" %}
{% block body %}
    <div class="section">
        <h5>Add New Character</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="row">
                    <div class="input-field col s12">
                        {{ field.errors }}
                        {{ field }}
                        {{ field.label_tag }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </div>

            {% endfor %}
            <button class="btn waves-effect waves-light" type="submit" value="Submit">
                Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
{% endblock %}

goosetools/users/templates/users/new_group.html
{% extends "core/base.html" %}
{% load materializecss %}
{% load static %}
{% block body %}
    <div class="section">
        <h5>Create New User Group</h5>
    </div>
    <div class="divider"></div>
    <div class="section">
        {% if form.non_field_errors %}
            <div class="row">
                <div class="col s12 m5">
                    <div class="card-panel red darken-1">
                    <span class="white-text">
                        <b>Errors with form:</b>
                    <ul class="errors">
                        {% for error in form.non_field_errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                    </span>
                    </div>
                </div>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {{ form.name|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.description|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.manually_given|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row" id="role_id">
                {{ form.required_discord_role_id|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <div class="row">
                {{ form.permissions|materializecss:'s12 m12, icon=directions_boat' }}
            </div>
            <button class="btn waves-effect waves-light" type="submit" value="Submit">
                Create Group
                <i class="material-icons right">send</i>
            </button>
            <br/>
        </form>
    </div>
{% endblock %}

{% block extrafooter %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <script>
    $(document).ready(function () {
        function hide_roles_if_manually_given() {
            if (this.checked) {
                $("#role_id").hide()
            } else {
                $("#role_id").show()
            }
        }

        $("#id_manually_given").change(hide_roles_if_manually_given).trigger("change")

    })
    </script>

{% endblock %}

goosetools/users/templates/users/refresh_discord_groups.html
{% extends "core/base.html" %}
{% block body %}
    <div class="section">
        <h4>Trigger Manual Discord Permissions Sync</h4>
        <p>This gets all users from the discord server and assigns them {{ SITE_NAME }}
            groups which they have the discord role for. This script runs automatically
            once per hour however you can trigger it manually now if you wish.</p>
    </div>
    {% if output %}
        <div class="section">
            {{ output|linebreaks }}
        </div>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        <button class="btn waves-effect waves-light green" type="submit" value="Submit">
            Start Sync (may take a long time)
        </button>
    </form>

{% endblock %}

goosetools/users/templates/users/signup.html
{% extends "core/base.html" %}

{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% trans "Signup" %}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col s12 center">
            {% if not corp.sign_up_form %}
                <h1>Application Form for {{ corp.name_with_with_corp_tag }} </h1>
            {% else %}
                <h1>{{ corp.sign_up_form.title }}</h1>
            {% endif %}
            {% if not corp.sign_up_form.description %}
                <p>Please fill in the fields below to submit your application
                    to {{ SITE_NAME }}. <br/>
                    If you need any help please ask on the discord server.</p>
            {% else %}
                <p>
                    {{ corp.sign_up_form.description|linebreaks }}
                </p>
            {% endif %}
            <b>You are applying to join <span
                    class="green-text">{{ corp.name_with_corp_tag }}</span>. Once you
                have submitted this application go apply in-game.</b>
            {% if form.non_field_errors or corp_form.non_field_errors %}
                <div class="card-panel red darken-1">
                <span class="white-text">
                    <b>Errors with form:</b>
                <ul class="errors">
                    {% for error in form.non_field_errors %}
                        <li>{{ error|escape }}</li>
                    {% endfor %}
                    {% for error in corp_form.non_field_errors %}
                        <li>{{ error|escape }}</li>
                    {% endfor %}
                </ul>
                </span>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <!-- Display Form -->
            <form action="" method="post">
                {% csrf_token %}
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}"
                           value="{{ redirect_field_value }}"/>
                {% endif %}
                <ul class="collection">
                    {% for field in corp_form %}
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s12">
                                    {{ field|materializecss }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    {% for field in form %}
                        <li class="collection-item">
                            <div class="row">
                                <div class="col s12">
                                    {{ field|materializecss }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    <li class="collection-item center">
                        <button class="green btn waves-btn btn-large"
                                id="sign_up_button"
                                type="submit">{% trans "Submit Application" %} &raquo;
                        </button>
                    </li>
                </ul>
            </form>
        </div>
    </div>
{% endblock %}

{% block extrafooter %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"
            type="text/javascript"></script>
    <link href="{% static 'admin/css/vendor/select2/select2.min.css' %}" type="text/css"
          media="screen" rel="stylesheet">
    <script src="{% static 'admin/js/vendor/select2/select2.full.js' %}"
            type="text/javascript"></script>

    <script>
    $(document).ready(function () {
        $('#id_timezone').select2()
    })
    </script>

{% endblock %}